apiVersion: v1
kind: Service
metadata:
  name: yblog-service
spec:
  type: NodePort
  selector:
    app: yblog
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
  