apiVersion: v1
kind: ConfigMap
metadata:
  name: yblog-config
data:
  .env: |
    APP_NAME=YBlog
    APP_ENV=local
    APP_KEY=33446a9dcf9ea060a0a6532b166da32f304af0de
    APP_DEBUG=true
    APP_URL=https://blog.010417.xyz
    APP_LOG_LEVEL=debug
    APP_PORT=8000
    DB_CONNECTION=mysql
    DB_HOST=mysql-service
    DB_PORT=3306
    DB_DATABASE=yblog
    DB_USERNAME=root
    DB_PASSWORD=root
    SESSION_DRIVER=cookie
    SESSION_NAME=blog-session
  
  init.sql: |
    CREATE DATABASE IF NOT EXISTS yblog;
  
  config.yml: |
    tunnel: ee132b83-a230-4ad2-95c7-da3cfb4f96c5
    credentials-file: /etc/cloudflared/credentials/credentials.json

    ingress:
      - hostname: blog.010417.xyz
        service: http://yblog-service.default.svc.cluster.local:8000
      - service: http_status:404
  