apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  root_password: cm9vdA==  # echo -n "root" | base64
  credentials.json: eyJBY2NvdW50VGFnIjoiMjcxODVjMjE2OGYwZTllMTMwOTQ2NjI5MGYxMzFmMTMiLCJUdW5uZWxTZWNyZXQiOiJwMGg2OTUwWmU0UkltK0xOVFVJOFM1Z0s4cmU1TmZmODFMbzNsUlIrUVRFPSIsIlR1bm5lbElEIjoiZWUxMzJiODMtYTIzMC00YWQyLTk1YzctZGEzY2ZiNGY5NmM1IiwiRW5kcG9pbnQiOiIifQ==